### ISSUE TITLE
Extension project type has no debug type

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind-vscode#102]
**Environment:**
- Extension version (eg. `19.2.0`):
- Codewind version (eg. `19.02`):
- [VS Code version](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-find-the-vs-code-version) (eg. `1.32.1`):
 - OS:

**Describe the bug:**

This is probably related or followup to #67 

There appears to be no debug type associated with extension project type, and it falls through: https://github.com/eclipse/codewind-vscode/blob/master/dev/src/microclimate/project/ProjectType.ts#L87

**To Reproduce:**

**Comment by tetchel** [comment]
:+1:

**Comment by tetchel** [comment]
after discussing with andrew, the appsody debug support is a lot more complex than this, so i'd like to close this and create a feature/story for supporting debug for appsody microprofile and node projects.
