### ISSUE TITLE
Fix deliverable file name to be compatible with other Codewind projects

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind-vscode#114]
it would be better to have the same pattern for the deliverable file names 

i.e. 
codewind-0.2.0-theia_2019-07-10-1655.vsix -> codewind-theia-0.2.0-201907101655.vsix
codewind-0.2.0_2019-07-10-1650.vsix -> codewind-0.2.0-201907101650.vsix

**Comment by josephca** [comment]
@tetchel can you assign it to yourself? I couldn't for some reasons. :)

**Comment by tetchel** [comment]
can't because i'm not committer

**Comment by tetchel** [comment]
i think now that i've commented, you can? i remember reading that

**Comment by jopit** [comment]
Yes, once you've commented on an issue, it can be assigned to you
