### ISSUE TITLE
Would like to see the link to the tekton dashboard appear in the editor

### ISSUE THREAD

**Issue by tobespc** [eclipse/codewind-vscode#135]
There is an upcoming change to the api/v1/environment api from portal that will include the url of the tekton dashboard (if available).   I would like to see this exposed through the vscode plugin to be able to click through to the dashboard

**Comment by tetchel** [comment]
After some design discussion it sounds like this fits best in the Projects tree item, where we currently have the Create and Bind operations. Not sure yet whether to use a Tekton icon or a generic "deploy" type icon.

**Comment by tobespc** [comment]
The changes are now in codewind.  When you call the environment API, you should see something like this returned

{
    "running_on_icp": true,
    "user_string": null,
    "socket_namespace": "/default",
    "workspace_location": "/projects",
    "os_platform": "Linux",
    "tekton_dashboard_url": "9.20.195.90.nip.io"
}
