### ISSUE TITLE
Unable set desired workspace location for codewind.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [eclipse/codewind-vscode#217]
After installing the codewind extension in vscode-server the default workspace is creating inside the root directory. unable to change the workspace location. Workspace location is hardcoded inside the codewind extension.

**Comment by tetchel** [comment]
Issue moved to [eclipse/codewind #607](https://github.com/eclipse/codewind/issues/607) via [**ZenHub**](https://www.zenhub.com/)
