### ISSUE TITLE
Project creation is failing in Mac OS

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-vscode#46]
**Environment:**
- **Extension version:** Latest Dev Version
- **Codewind version:** Latest Dev Version
- **VS Code version:** 1.33.1 
- **OS:** MacOS Mojave 10.14.5

**Description:**
Project creation is failing in Mac OS.
![image](https://user-images.githubusercontent.com/49531960/59782876-e5cced00-928c-11e9-862b-07d33692fcca.png)

**To Reproduce:**
(1) Initialize Codewind 
(2) Right click on Projects
(3) Click on "Create New Project"
(4) Select the project type
(5) Write the project name

The command palette could also be used to create the project.

**Logs:**
![image](https://user-images.githubusercontent.com/49531960/59783659-9b4c7000-928e-11e9-969c-2845e3d9213a.png)

**Comment by tetchel** [comment]
this sounds like the behaviour if the dockerhub images are installed, not the up-to-date artifactory images

did you follow these instructions?
https://ibm-cloud.slack.com/archives/C85THBQ6L/p1560436808196100

**Comment by sujeilyfonseca** [comment]
Tim helped me solve the problem on my machine. Project creation is now working.
