### ISSUE TITLE
Toggle indicator changes to "On", even if an error occurs when connecting to Codewind at http://localhost:9090/

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-vscode#51]
**Environment:**
- **Codewind version:** Latest Development Version
- **VS Code version:** 1.35.1
- **OS:** VM with Windows 10

**Description:**
The toggle indicator changes to "On", even if an error occurs when connecting to Codewind at http://localhost:9090/.  
![image](https://user-images.githubusercontent.com/49531960/59946254-01c0c200-9438-11e9-87cf-5a63606feb77.png)

**Steps:**
1. Stop Codewind
2. Right click on "Remove Codewind Images"
3. Windows runtime error occurred 
4. Start Codewind 
5. Connection failed 

**Log:**
[codewind-tools.log](https://github.com/eclipse/codewind-vscode/files/3315839/codewind-tools.log)

@jagraj

**Comment by tetchel** [comment]
not a bug but i agree this design is bad

**Comment by tetchel** [comment]
please upload repro steps and logs for how you got into this state

**Comment by sujeilyfonseca** [comment]
I updated the issue and included the "codewind-tools.log" file.
