### ISSUE TITLE
Java project failed to start in debug mode from codewind theia editor

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-vscode#54]
I have java project running in my che workspace with codewind install. There is option available to start the Java project in debug mode , when I try to start project in debug mode and it fails with this message in the notification panel.

![image](https://user-images.githubusercontent.com/713849/59982367-e47a2800-95de-11e9-8839-fa1574260b7f.png)

Here are the logs from my cluster..

[che.txt](https://github.com/eclipse/codewind-vscode/files/3318618/che.txt)
[che-machine.txt](https://github.com/eclipse/codewind-vscode/files/3318619/che-machine.txt)
[codewind.txt](https://github.com/eclipse/codewind-vscode/files/3318620/codewind.txt)
[editor.txt](https://github.com/eclipse/codewind-vscode/files/3318621/editor.txt)
[sidecar.txt](https://github.com/eclipse/codewind-vscode/files/3318622/sidecar.txt)

**Comment by jopit** [comment]
Fixed by this theia-specific version of the vscode extension: http://download.eclipse.org/codewind/codewind-vscode/master/3/codewind-0.2.0-theia_2019-06-24-1937.vsix
