### ISSUE TITLE
Some of the commands from codewind palette does not work from codewind theia editor.

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-vscode#55]
Hi,

I am trying to invoke some of the commands available in theia editor and they do not work.
Do we support all these commands in the palette   from codewind che theia editor.?

Please take a look at these commands from the following screenshot. 

![image](https://user-images.githubusercontent.com/713849/59982593-c7dfef00-95e2-11e9-8a30-4e6a978ffce0.png)

**Comment by jopit** [comment]
Not all commands are supported yet when running in Kube.  We should remove these if possible.

**Comment by jopit** [comment]
Fixed by this theia-specific version of the vscode extension: http://download.eclipse.org/codewind/codewind-vscode/master/3/codewind-0.2.0-theia_2019-06-24-1937.vsix
