### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by MohamedGawad** [eclipse/codewind-vscode#550]
Issue Type: <b>Feature Request</b>

Error creating new project: {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"github.com","host":"github.com","port":443}

Extension version: 0.9.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:52:11.516Z)
OS version: Linux x64 4.18.0-80.el8.x86_64

**Comment by tetchel** [comment]
This looks like an automatically generated issue, but in case you see this: just run the command again and it should work.

Likely github was not resolvable by your DNS for a short time.
