### ISSUE TITLE
Project type name for Generic Docker projects

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-vscode#64]
![image](https://user-images.githubusercontent.com/8888438/60103679-0930e580-972e-11e9-88c6-46b6f1be3f9d.png)

"Other"
"Other (Generic Docker)"
"Generic Docker"

???

**Comment by deboer-tim** [comment]
Not a huge fan of 'generic'. Maybe 'simple' or 'basic' or something else?

We should also use 'container', not Docker.

**Comment by tetchel** [comment]
Basic Container? Simple Container? 
Other (Basic Container) ?

**Comment by maysunfaisal** [comment]
I vote for `Other`, looks aesthetically pleasing. And i also support Tim's argument that all projects are Docker projects. It doesn't matter what terminology we use internally, but showing it as `Other` to the users is plain and simple.

**Comment by elsony** [comment]
I think we need to have something more than just Other.  It is more than just internal terminology. The user will need to have Dockerfile as part of their application run. Without telling them that we are running as a container, it will be strange for them to find later that they have validation error on missing Dockerfile if their app doesn't have it.  So if we are going with Other, then I would vote for "Other (Basic Container)".

**Comment by jgwest** [comment]
Custom Container? Custom Containerized App? Custom Dockerfile?

**Comment by tetchel** [comment]
forgot to close - It was changed to `Other (Basic Container)` in the referenced commit
