### ISSUE TITLE
[ICP] Project creation not cancelled upon cancelling

### ISSUE THREAD

**Issue by DavidG1011** [eclipse/codewind-vscode#66]
Platform: ICP

Reproduce:
1. Create new project from Codewind plugin.
2. Click cancel on project creation status bar.

Result: Creation status bar closes. Project creation not cancelled.

![statusbar](https://user-images.githubusercontent.com/30476587/60117084-68e7ba80-9747-11e9-8af0-48226acbf5b2.png)

![Screen Shot 2019-06-25 at 12 37 56 PM](https://user-images.githubusercontent.com/30476587/60117133-756c1300-9747-11e9-9171-ef6da8d27b04.png)

**Comment by tetchel** [comment]
hey, this is a theia bug. there are a number of actions that provide the 'cancel' button erroneously. this will not be fixed on my end; i will open a bug for them next week.

**Comment by tetchel** [comment]
https://github.com/theia-ide/theia/issues/5578

**Comment by DavidG1011** [comment]
Sounds good. Thanks Tim.
