### ISSUE TITLE
Extension project type shows up as Unknown in overview page

### ISSUE THREAD

**Issue by makandre** [eclipse/codewind-vscode#67]
**Environment:**
- Extension version (eg. `19.2.0`):
- Codewind version (eg. `19.02`):
- [VS Code version](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-find-the-vs-code-version) (eg. `1.32.1`):
 - OS:

**Describe the bug:**

I'm building an extension for Codewind that brings in a new project type.  On the project overview page, the type shows as unknown however:

![image](https://user-images.githubusercontent.com/17596240/60124573-e3b8d180-9757-11e9-9f7d-e8b3068d3f46.png)

I think it's because in `getType`, it's falling in the `else` block since it is not an internal type:

https://github.com/eclipse/codewind-vscode/blob/64c13da9b4259afc66781f5d1816482dac0c0843/dev/src/microclimate/project/ProjectType.ts#L67

**To Reproduce:**

**Comment by jopit** [comment]
We shouldn't include non-open-source project types in open-source codewind.

**Comment by makandre** [comment]
Thanks for the speedy fix.
