### ISSUE TITLE
intermittent 'no projects' when there are projects after stop/start

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind-vscode#71]
From @AndyRWatson

When starting and stopping codewind from within the vscode UI I intermittently get the restart showing none of my previous projects. I have run a docker ps and see all the containers restarted and confirmed localhost://9090/health returns ok and the project are running/accessable,

Restart of vscode and the projects reappear (no restart of docker containers).

refresh fixes it

**Comment by tetchel** [comment]
since refresh fixes it, it is likely the plugin is hitting `api/v1/projects` before it is ready.

**Comment by AndyRWatson** [comment]
Thanks @tetchel
