### ISSUE TITLE
[SVT] Error message block appears when opening Java liberty project web page example path

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind-vscode#73]
**Environment:**
- Extension version (eg. `19.2.0`): 0.2.0
- Codewind version (eg. `19.02`): pulled 6/20/19 (are we able to see the version in vscode?)
- [VS Code version](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-find-the-vs-code-version) (eg. `1.32.1`): Version 1.35.1 (1.35.1)
 - OS: MacOS Mojave, Version 10.14.5

**Describe the bug:**

UI shows error block when opening up java microprofile app endpoint on mac local, like in the old MSB/early microclimate days.

![image](https://user-images.githubusercontent.com/13971834/60147238-ae81a300-979a-11e9-91c7-830c8d7f27ba.png)

**To Reproduce:**

1. create java project
2. make edits
3. append path: `http://localhost:<application_endpoint>/v1/example#`

**Comment by tetchel** [comment]
No idea what this is but it's certainly not vs code, please move to https://github.com/eclipse/codewind

**Comment by tetchel** [comment]
>  (are we able to see the version in vscode?)

Good question. Codewind doesn't have proper versioning yet so the extension version is enough.

**Comment by jopit** [comment]
This actually looks to me like a problem in the (modified) application itself, i.e. the app is sending bad JSON to the browser with some weird character after the opening square bracket.

I'm going to close this on that basis, if that's not the problem, please reopen against codewind -- as Tim said, it's not an IDE issue.

**Comment by tetchel** [comment]
I think it's actually not JSON at all, it's a java array `.toString()`'d, and the browser is falsey trying to parse it as JSON
