### ISSUE TITLE
[SVT] Project type icons on project info pages are broken

### ISSUE THREAD

**Issue by beccabau** [eclipse/codewind-vscode#74]
**Environment:**
- Extension version (eg. `19.2.0`): 0.2.0
- Codewind version (eg. `19.02`): pulled 6/20/19 (are we able to see the version in vscode?)
- [VS Code version](https://code.visualstudio.com/docs/supporting/faq#_how-do-i-find-the-vs-code-version) (eg. `1.32.1`): Version 1.35.1 (1.35.1)
 - OS: MacOS Mojave, Version 10.14.5

**Describe the bug:**

Project type icons for all project types show as broken images on the overview pages.
![image](https://user-images.githubusercontent.com/13971834/60147513-b261f500-979b-11e9-9a0e-1404828eb1c9.png)
![image](https://user-images.githubusercontent.com/13971834/60147537-c9084c00-979b-11e9-89ca-f80838f0b332.png)
![image](https://user-images.githubusercontent.com/13971834/60147541-cdcd0000-979b-11e9-9223-ab157b89a893.png)

etc

**To Reproduce:**

1. create project
2. click info button next to each project
3. view project overview page

**Comment by tetchel** [comment]
is this in vs code, or theia?

**Comment by beccabau** [comment]
vscode, sorry

**Comment by tetchel** [comment]
hmm, those icons certainly work for me so please make sure your vsix is up to date

**Comment by beccabau** [comment]
Okay, turns out the uninstalls weren't complete before, so I had to manually clear out images and uninstall. In further testing, I'll see if this behavior repeats itself.
