### ISSUE TITLE
Java Microprofile projects do not present some logs on Windows 10

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-vscode#76]
**Environment:**
- **Codewind version:** Latest Development Version (codewind-0.2.0_2019-06-26-0052.vsix)
- **VS Code version:** 1.35.1
- **OS:** VM with Windows 10

**Description:**
Java Microprofile projects do not present some logs (messages.logs, app.log, and console.log). If you click "Show all logs" and try to see these logs, the message "Waiting for Codewind to send logs..." appears indefinitely. On the other hand, once a Java Microprofile project is created on Windows 10, the UI presents an error indicating "project-name: checking available logs failed: Internal error occurred, status code: 500".

![image](https://user-images.githubusercontent.com/49531960/60190133-233af880-9800-11e9-81f8-1ba9fc5b6c87.png)

![image](https://user-images.githubusercontent.com/49531960/60190153-29c97000-9800-11e9-8812-f6c528497392.png)

![image](https://user-images.githubusercontent.com/49531960/60190170-30f07e00-9800-11e9-894e-65caf60f0a02.png)

![image](https://user-images.githubusercontent.com/49531960/60190177-35b53200-9800-11e9-9aa0-bf2abfa915c3.png)
 
**Steps:**
1. Install and start Codewind
2. Create a Java Microprofile project
3. Right click on the created project
4. Click on "Show all logs"
5. Verify the logs (messages.logs, app.log, and console.log)

**Log:**
[codewind.log](https://github.com/eclipse/codewind-vscode/files/3330620/codewind.log)
[codewind-pfe.txt](https://github.com/eclipse/codewind-vscode/files/3330951/codewind-pfe.txt)

@jagraj

**Comment by tetchel** [comment]
please upload pfe logs and move this to `eclipse/codewind`. 500 means the error is in portal or file watcher.

**Comment by sujeilyfonseca** [comment]
Issue moved to [eclipse/codewind #7](https://github.com/eclipse/codewind/issues/7) via [**ZenHub**](https://www.zenhub.com/)
