### ISSUE TITLE
"Windows-style path" errors on Windows 10

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind-vscode#84]
**Environment:**
- **Codewind version:** Latest Development Version
- **VS Code version:**  Code 1.35.1
- **OS:** VM with Windows 10

**Description:** 
Several projects failed to build in VS Code (Windows 10). The file watcher log has several error messages due to not supporting Windows-style paths.

<img width="841" alt="Screen Shot 2019-06-24 at 10 56 24 AM" src="https://user-images.githubusercontent.com/49531960/60039941-e1864280-9685-11e9-8482-9cba8f903648.png">

![image](https://user-images.githubusercontent.com/49531960/60040567-527a2a00-9687-11e9-8511-f8a7e68effc8.png)

![image](https://user-images.githubusercontent.com/49531960/60040527-36768880-9687-11e9-8248-d5163efed7eb.png)

**Logs:**
[codewind-tools.log](https://github.com/eclipse/codewind/files/3321977/codewind-tools.log)
[filewatcherd-1.log](https://github.com/eclipse/codewind/files/3321978/filewatcherd-1.log)

@jagraj

**Comment by jopit** [comment]
@tetchel  could you take a look at this please
