### ISSUE TITLE
Projects missing from codewind palette in codewind che deployed in ICP

### ISSUE THREAD

**Issue by jagraj** [eclipse/codewind-vscode#85]
After creating all project types in codewind che workspace, the projects started missing from palette when builds are in progress. I am using latest images and plugins and here is the devfile that i am using.

https://raw.githubusercontent.com/eclipse/codewind-che-plugin/master/devfiles/latest/devfile.yaml

Logs -:
[che.txt](https://github.com/eclipse/codewind-vscode/files/3332933/che.txt)
[che-machine.txt](https://github.com/eclipse/codewind-vscode/files/3332934/che-machine.txt)
[codewind.txt](https://github.com/eclipse/codewind-vscode/files/3332935/codewind.txt)
[editor.txt](https://github.com/eclipse/codewind-vscode/files/3332936/editor.txt)
[sidecar.txt](https://github.com/eclipse/codewind-vscode/files/3332937/sidecar.txt)

![image](https://user-images.githubusercontent.com/713849/60234195-3afe9500-9871-11e9-9adb-8b887e4bffb7.png)

![image](https://user-images.githubusercontent.com/713849/60234316-beb88180-9871-11e9-8c2d-20812b5908d7.png)

![image](https://user-images.githubusercontent.com/713849/60234327-ce37ca80-9871-11e9-88f3-192968922669.png)

**Comment by jagraj** [comment]
I also invoked refresh command from the projects view list and it says refreshing projects from localhost url with 9090. My understanding is, this should invoke refresh ingress endpoint.

Here is the message displayed after "Refresh" command request..

`Refreshed Codewind at https://localhost:9090/.`

**Comment by jopit** [comment]
@tetchel could you please look into this

**Comment by tetchel** [comment]
```

root ERROR [hosted-plugin: 73] [ERRO: 03:36:57.738 extension.js.on():43]: Unhandled promise rejection: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.replyOK (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:280:103)
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:158:51
    at process._tickCallback (internal/process/next_tick.js:68:7)
```


This is https://github.com/theia-ide/theia/issues/4975 
which is the bug I had them fix so we could run our extension... it seems to have regressed

**Comment by tetchel** [comment]
We need a way to lock the theia version

**Comment by tetchel** [comment]
The breaking change is theia-ide/theia#5556

I will open a theia bug shortly

**Comment by ericdylanpeters2** [comment]
@jagraj please verify, thanks!

**Comment by jagraj** [comment]
this issue has been fixed in latest vscode-plugin but we still have issue the PFE (https://github.ibm.com/dev-ex/iterative-dev/issues/1199) and this will be addressed after tech preview.

**Comment by tetchel** [comment]
that's an unrelated issue, but thanks jag.
