### ISSUE TITLE
Enable the "Open App" action when the App State is "Starting"

### ISSUE THREAD

**Issue by keithchong** [eclipse/codewind-vscode#98]
The logic in determining whether an app is "Running" versus "Starting" is not bulletproof. 

I've encountered cases when the App is actually running fine, but the state is still at "Starting", but I had to update the .cw-settings file and add a valid path to contextRoot.

In one case, my app was running perfectly fine even though an "empty context root" returned a 404.

Consider enabling the "Open App" when the state is at "Starting". That way, the browser comes up with the proper port and then I can append the valid paths.

**Comment by tetchel** [comment]
agreed

**Comment by keithchong** [comment]
Think that bug label was added automatically?

Here is the corresponding eclipse bug: https://github.com/eclipse/codewind-eclipse/issues/135

Note the action name is different too.

**Comment by tetchel** [comment]
if you select the bug template, it adds bug label, if you select "open a regular issue" it skips the template
